name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-release
          path: .pio/build/esp32/firmware.bin
          if-no-files-found: error
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: firmware-release
    - name: Create draft release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
          *.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
